#!/usr/bin/env python3
# origin: lemoncloud-io/knowledge@01f358b:projects/second-brain/config/scripts/generate_raw_index.py
"""Generate docs/raw-index.md — the raw/ preservation index.

Run from the vault root. Regenerated by the vault-lint pass; the output file is
never hand-edited. Contract: docs/raw-layout.md § 색인.

Reads raw/ filenames + frontmatter only; never modifies anything under raw/.
"""

import datetime
import glob
import os
import re
import subprocess
import sys

SCAN_GLOBS = ["wiki/**/*.md", "outputs/**/*.md", "projects/**/*.md", "areas/**/*.md"]
ROOT_CAP_HINT = 200  # docs/raw-layout.md: 서브폴더 재구조화 재검토 임계


def fail(msg: str) -> None:
    sys.exit(f"generate_raw_index: {msg}")


def first_add_dates() -> dict:
    """First git add date per current raw/*.md path (renames counted as adds)."""
    out = subprocess.run(
        ["git", "log", "--reverse", "--no-renames", "--diff-filter=A",
         "--name-only", "--format=@%ad", "--date=short", "--", "raw/"],
        capture_output=True, text=True,
    ).stdout
    dates, current = {}, None
    for line in out.splitlines():
        if line.startswith("@"):
            current = line[1:]
        elif line.startswith("raw/") and line.endswith(".md") and "/" not in line[4:]:
            dates.setdefault(line[4:], current)
    return dates


def frontmatter_source(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as fh:
            head = fh.read(3000)
    except OSError:
        return ""
    if not head.startswith("---"):
        return ""
    m = re.search(r'^source:\s*"?([^"\n]+?)"?\s*$', head, re.M)
    return m.group(1).strip() if m else ""


def main() -> None:
    if not (os.path.isdir("raw") and os.path.isfile("VAULT_RULES.md")):
        fail("run from the vault root (raw/ + VAULT_RULES.md required)")

    raws = sorted(f for f in os.listdir("raw") if f.endswith(".md"))
    shots = len(glob.glob("raw/screenshots/**/*.*", recursive=True))

    corpus = {}
    for pattern in SCAN_GLOBS:
        for path in glob.glob(pattern, recursive=True):
            try:
                corpus[path] = open(path, encoding="utf-8").read()
            except OSError:
                pass

    added = first_add_dates()
    entries, sources = [], {}
    for name in raws:
        refs = sorted(p for p, text in corpus.items() if f"raw/{name}" in text)
        src = frontmatter_source(f"raw/{name}")
        if src:
            sources.setdefault(src, []).append(name)
        entries.append({
            "name": name,
            "added": added.get(name, "untracked"),
            "source": src,
            "refs": refs,
        })

    orphans = [e["name"] for e in entries if not e["refs"]]
    dup_urls = {u: fs for u, fs in sources.items()
                if len(fs) > 1 and u.startswith("http")}

    def ref_label(path: str) -> str:
        if path.startswith("wiki/") and path.count("/") == 1:
            return f"[[{os.path.basename(path)[:-3]}]]"
        return f"`{path}`"

    def src_label(src: str) -> str:
        if src.startswith("http"):
            return f"[src]({src})"
        return src if src else "(frontmatter 없음)"

    by_month = {}
    for e in entries:
        month = e["added"][:7] if e["added"] != "untracked" else "untracked"
        by_month.setdefault(month, []).append(e)

    today = datetime.date.today().isoformat()
    lines = [
        "# Raw Index",
        "",
        "`raw/` 보존소의 자동 생성 색인 — **수동 편집 금지.**",
        "재생성: vault 루트에서 `python3 projects/second-brain/config/scripts/generate_raw_index.py`",
        "(`vault-lint` 패스가 실행). 계약: `docs/raw-layout.md`.",
        "",
        f"- 생성: {today} · 루트 파일 {len(raws)} (서브폴더 재구조화 임계 {ROOT_CAP_HINT})"
        f" · screenshots 레인 {shots}개 항목",
        f"- 오펀(참조 0건): {len(orphans)} · source URL 중복: {len(dup_urls)}",
    ]
    if orphans:
        lines += ["", "## 오펀 — lint 리포트 대상", ""]
        lines += [f"- `raw/{n}`" for n in orphans]
    if dup_urls:
        lines += ["", "## source URL 중복 — lint 리포트 대상", ""]
        for url, files in sorted(dup_urls.items()):
            lines.append(f"- {url}")
            lines += [f"  - `raw/{n}`" for n in files]
    for month in sorted(by_month, reverse=True):
        group = sorted(by_month[month], key=lambda e: (e["added"], e["name"]), reverse=True)
        lines += ["", f"## {month} 유입 ({len(group)})", ""]
        for e in group:
            refs = ", ".join(ref_label(r) for r in e["refs"]) or "—"
            lines.append(f"- **{e['name']}** · {e['added']} · {src_label(e['source'])} · → {refs}")
    lines.append("")

    with open("docs/raw-index.md", "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"docs/raw-index.md written: {len(raws)} files, "
          f"{len(orphans)} orphans, {len(dup_urls)} duplicate URLs")


if __name__ == "__main__":
    main()
